/* Generated by Pyrex 0.9.8.5 on Tue Jul  1 14:25:15 2014 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "Definitions.h"
#include "Boolean.h"
#include "Cardinal.h"
#include "Integer.h"
#include "Real.h"
#include "StateVector.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from pCore.cDefinitions */


/* Declarations from ContinuumElectrostatics.StateVector */

struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector {
  PyObject_HEAD
  StateVector *cObject;
};


static PyTypeObject *__pyx_ptype_23ContinuumElectrostatics_11StateVector_StateVector = 0;

/* Declarations from implementation of ContinuumElectrostatics.StateVector */


static char __pyx_k1[] = "CLibraryError";
static char __pyx_k2[] = "Vector index out of range.";
static char __pyx_k3[] = "Vector index out of range or wrong value.";
static char __pyx_k4[] = "meadSites";
static char __pyx_k5[] = "Memory allocation failure.";
static char __pyx_k6[] = "instances";
static char __pyx_k7[] = "LogFileActive";
static char __pyx_k8[] = "GetTable";
static char __pyx_k9[] = "columns";
static char __pyx_k10[] = "Start";
static char __pyx_k11[] = "Title";
static char __pyx_k12[] = "State vector";
static char __pyx_k13[] = "Heading";
static char __pyx_k14[] = "Site";
static char __pyx_k15[] = "columnSpan";
static char __pyx_k16[] = "Instance";
static char __pyx_k17[] = "  ";
static char __pyx_k18[] = " @";
static char __pyx_k19[] = "Entry";
static char __pyx_k20[] = "segName";
static char __pyx_k21[] = "resName";
static char __pyx_k22[] = "%d";
static char __pyx_k23[] = "resSerial";
static char __pyx_k24[] = "label";
static char __pyx_k25[] = "Stop";
static char __pyx_k26[] = "Site %s %d not found.";
static char __pyx_k27[] = "pCore";
static char __pyx_k28[] = "logFile";
static char __pyx_k29[] = "$Id$";
static char __pyx_k30[] = "__lastchanged__";

static PyObject *__pyx_n_CLibraryError;
static PyObject *__pyx_n_Entry;
static PyObject *__pyx_n_GetTable;
static PyObject *__pyx_n_Heading;
static PyObject *__pyx_n_Instance;
static PyObject *__pyx_n_LogFileActive;
static PyObject *__pyx_n_Site;
static PyObject *__pyx_n_Start;
static PyObject *__pyx_n_Stop;
static PyObject *__pyx_n_Title;
static PyObject *__pyx_n___lastchanged__;
static PyObject *__pyx_n_columnSpan;
static PyObject *__pyx_n_columns;
static PyObject *__pyx_n_instances;
static PyObject *__pyx_n_label;
static PyObject *__pyx_n_logFile;
static PyObject *__pyx_n_meadSites;
static PyObject *__pyx_n_pCore;
static PyObject *__pyx_n_resName;
static PyObject *__pyx_n_resSerial;
static PyObject *__pyx_n_segName;

static PyObject *__pyx_k2p;
static PyObject *__pyx_k3p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k17p;
static PyObject *__pyx_k18p;
static PyObject *__pyx_k22p;
static PyObject *__pyx_k26p;
static PyObject *__pyx_k29p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_CLibraryError, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_Entry, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_GetTable, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_Heading, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_Instance, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_LogFileActive, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_Site, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_Start, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_Stop, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_Title, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n___lastchanged__, 1, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_n_columnSpan, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_columns, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_instances, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_label, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_logFile, 1, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_n_meadSites, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_pCore, 1, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_n_resName, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_resSerial, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_segName, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k2p, 0, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k17p, 0, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_k18p, 0, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k22p, 0, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_k26p, 0, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_k29p, 0, __pyx_k29, sizeof(__pyx_k29)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;
static PyObject *__pyx_d2;
static PyObject *__pyx_d3;


/* Implementation of ContinuumElectrostatics.StateVector */

static Py_ssize_t __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__(PyObject *__pyx_v_self); /*proto*/
static Py_ssize_t __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__(PyObject *__pyx_v_self) {
  Py_ssize_t __pyx_r;
  Py_INCREF(__pyx_v_self);
  __pyx_r = ((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->length;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index); /*proto*/
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index) {
  PyObject *__pyx_v_item;
  PyObject *__pyx_r;
  Integer __pyx_1;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);
  __pyx_v_item = Py_None; Py_INCREF(Py_None);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":23 */
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(StateVector_GetItem(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_v_item);
  __pyx_v_item = __pyx_2;
  __pyx_2 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":24 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_item, __pyx_2, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_3 = __pyx_3 < 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_3) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CLibraryError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    Py_INCREF(__pyx_k2p);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k2p);
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":26 */
  Py_INCREF(__pyx_v_item);
  __pyx_r = __pyx_v_item;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_item);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  return __pyx_r;
}

static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value); /*proto*/
static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value) {
  PyObject *__pyx_v_ok;
  int __pyx_r;
  Integer __pyx_1;
  Integer __pyx_2;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);
  Py_INCREF(__pyx_v_value);
  __pyx_v_ok = Py_None; Py_INCREF(Py_None);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":31 */
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_value); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(StateVector_SetItem(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_1,__pyx_2)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_v_ok);
  __pyx_v_ok = __pyx_3;
  __pyx_3 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":32 */
  __pyx_4 = PyObject_IsTrue(__pyx_v_ok); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_5 = (!__pyx_4);
  if (__pyx_5) {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_CLibraryError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    Py_INCREF(__pyx_k3p);
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_k3p);
    __pyx_7 = PyObject_CallObject(__pyx_3, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __Pyx_Raise(__pyx_7, 0, 0);
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.__setitem__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ok);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  Py_DECREF(__pyx_v_value);
  return __pyx_r;
}

static void __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);
  StateVector_Deallocate(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Increment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Increment[] = "Generate a new state incrementing the state vector.\n\n    Return False after the incrementation has finished.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Increment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(StateVector_Increment(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.Increment");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Reset(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Reset[] = "Set all components of the vector to zero.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Reset(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  StateVector_Reset(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum[] = "Set all components of the vector to their maximum values.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  StateVector_ResetToMaximum(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_meadModel = 0;
  PyObject *__pyx_v_nsites;
  PyObject *__pyx_v_siteIndex;
  PyObject *__pyx_v_site;
  PyObject *__pyx_v_ninstances;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  Integer __pyx_3;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"meadModel",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_meadModel)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_meadModel);
  __pyx_v_nsites = Py_None; Py_INCREF(Py_None);
  __pyx_v_siteIndex = Py_None; Py_INCREF(Py_None);
  __pyx_v_site = Py_None; Py_INCREF(Py_None);
  __pyx_v_ninstances = Py_None; Py_INCREF(Py_None);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":60 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_meadModel, __pyx_n_meadSites); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_2 = PyObject_Length(__pyx_1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromSsize_t(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_v_nsites);
  __pyx_v_nsites = __pyx_1;
  __pyx_1 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":61 */
  __pyx_3 = PyInt_AsLong(__pyx_v_nsites); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  ((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject = StateVector_Allocate(__pyx_3);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":62 */
  __pyx_4 = (((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject == NULL);
  if (__pyx_4) {
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CLibraryError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_INCREF(__pyx_k5p);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k5p);
    __pyx_6 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_6, 0, 0);
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":65 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_meadModel, __pyx_n_meadSites); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_6 = PyObject_CallObject(((PyObject *)(&PyEnum_Type)), __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_1 = PyObject_GetIter(__pyx_6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  for (;;) {
    __pyx_5 = PyIter_Next(__pyx_1);
    if (!__pyx_5) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
      break;
    }
    __pyx_6 = PyObject_GetIter(__pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_5 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    Py_DECREF(__pyx_v_siteIndex);
    __pyx_v_siteIndex = __pyx_5;
    __pyx_5 = 0;
    __pyx_5 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    Py_DECREF(__pyx_v_site);
    __pyx_v_site = __pyx_5;
    __pyx_5 = 0;
    if (__Pyx_EndUnpack(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":66 */
    __pyx_5 = PyObject_GetAttr(__pyx_v_site, __pyx_n_instances); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    __pyx_2 = PyObject_Length(__pyx_5); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_6 = PyInt_FromSsize_t(__pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ninstances);
    __pyx_v_ninstances = __pyx_6;
    __pyx_6 = 0;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":67 */
    __pyx_5 = PyInt_FromLong(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    __pyx_6 = PyNumber_Subtract(__pyx_v_ninstances, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_3 = PyInt_AsLong(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_2 = PyInt_AsSsize_t(__pyx_v_siteIndex); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    (((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->maxvector[__pyx_2]) = __pyx_3;
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_nsites);
  Py_DECREF(__pyx_v_siteIndex);
  Py_DECREF(__pyx_v_site);
  Py_DECREF(__pyx_v_ninstances);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_meadModel);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Print(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Print[] = "Print the state vector.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Print(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_meadModel = 0;
  PyObject *__pyx_v_title = 0;
  PyObject *__pyx_v_log = 0;
  PyObject *__pyx_v_table;
  PyObject *__pyx_v_siteIndex;
  PyObject *__pyx_v_substate;
  PyObject *__pyx_v_j;
  PyObject *__pyx_v_selectedSiteIndex;
  PyObject *__pyx_v_site;
  PyObject *__pyx_v_instanceIndex;
  PyObject *__pyx_v_instance;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  PyObject *__pyx_11 = 0;
  long __pyx_12;
  Integer __pyx_13;
  long __pyx_14;
  Integer __pyx_15;
  Integer __pyx_16;
  Py_ssize_t __pyx_17;
  static char *__pyx_argnames[] = {"meadModel","title","log",0};
  __pyx_v_meadModel = __pyx_d1;
  __pyx_v_title = __pyx_d2;
  __pyx_v_log = __pyx_d3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_meadModel, &__pyx_v_title, &__pyx_v_log)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_meadModel);
  Py_INCREF(__pyx_v_title);
  Py_INCREF(__pyx_v_log);
  __pyx_v_table = Py_None; Py_INCREF(Py_None);
  __pyx_v_siteIndex = Py_None; Py_INCREF(Py_None);
  __pyx_v_substate = Py_None; Py_INCREF(Py_None);
  __pyx_v_j = Py_None; Py_INCREF(Py_None);
  __pyx_v_selectedSiteIndex = Py_None; Py_INCREF(Py_None);
  __pyx_v_site = Py_None; Py_INCREF(Py_None);
  __pyx_v_instanceIndex = Py_None; Py_INCREF(Py_None);
  __pyx_v_instance = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_LogFileActive); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_INCREF(__pyx_v_log);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_log);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    __pyx_4 = PyObject_IsTrue(__pyx_v_meadModel); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    if (__pyx_4) {

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":74 */
      __pyx_1 = PyObject_GetAttr(__pyx_v_log, __pyx_n_GetTable); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_6 = PyInt_FromLong(7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_7 = PyInt_FromLong(7); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_8 = PyInt_FromLong(8); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_9 = PyInt_FromLong(8); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_10 = PyInt_FromLong(2); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      __pyx_11 = PyList_New(6); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      PyList_SET_ITEM(__pyx_11, 0, __pyx_5);
      PyList_SET_ITEM(__pyx_11, 1, __pyx_6);
      PyList_SET_ITEM(__pyx_11, 2, __pyx_7);
      PyList_SET_ITEM(__pyx_11, 3, __pyx_8);
      PyList_SET_ITEM(__pyx_11, 4, __pyx_9);
      PyList_SET_ITEM(__pyx_11, 5, __pyx_10);
      __pyx_5 = 0;
      __pyx_6 = 0;
      __pyx_7 = 0;
      __pyx_8 = 0;
      __pyx_9 = 0;
      __pyx_10 = 0;
      if (PyDict_SetItem(__pyx_3, __pyx_n_columns, __pyx_11) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      __pyx_5 = PyEval_CallObjectWithKeywords(__pyx_1, __pyx_2, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_v_table);
      __pyx_v_table = __pyx_5;
      __pyx_5 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":75 */
      __pyx_6 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Start); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
      __pyx_7 = PyObject_CallObject(__pyx_6, 0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":76 */
      __pyx_4 = __pyx_v_title == Py_None;
      if (__pyx_4) {
        __pyx_8 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Title); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
        __pyx_9 = PyTuple_New(1); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
        Py_INCREF(__pyx_k12p);
        PyTuple_SET_ITEM(__pyx_9, 0, __pyx_k12p);
        __pyx_10 = PyObject_CallObject(__pyx_8, __pyx_9); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        Py_DECREF(__pyx_10); __pyx_10 = 0;
        goto __pyx_L4;
      }
      /*else*/ {
        __pyx_11 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Title); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
        __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
        Py_INCREF(__pyx_v_title);
        PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_title);
        __pyx_2 = PyObject_CallObject(__pyx_11, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
        Py_DECREF(__pyx_11); __pyx_11 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;
      }
      __pyx_L4:;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":81 */
      __pyx_3 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Heading); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      Py_INCREF(__pyx_n_Site);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_n_Site);
      __pyx_6 = PyDict_New(); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      __pyx_7 = PyInt_FromLong(3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      if (PyDict_SetItem(__pyx_6, __pyx_n_columnSpan, __pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      __pyx_8 = PyEval_CallObjectWithKeywords(__pyx_3, __pyx_5, __pyx_6); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_8); __pyx_8 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":82 */
      __pyx_9 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Heading); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      Py_INCREF(__pyx_n_Instance);
      PyTuple_SET_ITEM(__pyx_10, 0, __pyx_n_Instance);
      __pyx_11 = PyDict_New(); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      if (PyDict_SetItem(__pyx_11, __pyx_n_columnSpan, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_2 = PyEval_CallObjectWithKeywords(__pyx_9, __pyx_10, __pyx_11); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":84 */
      __pyx_13 = ((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->length;
      for (__pyx_12 = 0; __pyx_12 < __pyx_13; ++__pyx_12) {
        __pyx_7 = PyInt_FromLong(__pyx_12); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
        Py_DECREF(__pyx_v_siteIndex);
        __pyx_v_siteIndex = __pyx_7;
        __pyx_7 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":85 */
        Py_INCREF(__pyx_k17p);
        Py_DECREF(__pyx_v_substate);
        __pyx_v_substate = __pyx_k17p;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":87 */
        __pyx_4 = (((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->substate != NULL);
        if (__pyx_4) {
          __pyx_15 = ((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->slength;
          for (__pyx_14 = 0; __pyx_14 < __pyx_15; ++__pyx_14) {
            __pyx_3 = PyInt_FromLong(__pyx_14); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
            Py_DECREF(__pyx_v_j);
            __pyx_v_j = __pyx_3;
            __pyx_3 = 0;

            /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":89 */
            __pyx_16 = PyInt_AsLong(__pyx_v_j); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
            __pyx_5 = PyInt_FromLong(StateVector_GetSubstateItem(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_16)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
            Py_DECREF(__pyx_v_selectedSiteIndex);
            __pyx_v_selectedSiteIndex = __pyx_5;
            __pyx_5 = 0;

            /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":90 */
            if (PyObject_Cmp(__pyx_v_selectedSiteIndex, __pyx_v_siteIndex, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
            __pyx_4 = __pyx_4 == 0;
            if (__pyx_4) {
              Py_INCREF(__pyx_k18p);
              Py_DECREF(__pyx_v_substate);
              __pyx_v_substate = __pyx_k18p;
              goto __pyx_L10;
            }
            __pyx_L10:;
          }
          goto __pyx_L7;
        }
        __pyx_L7:;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":93 */
        __pyx_6 = PyObject_GetAttr(__pyx_v_meadModel, __pyx_n_meadSites); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
        __pyx_8 = PyObject_GetItem(__pyx_6, __pyx_v_siteIndex); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        Py_DECREF(__pyx_v_site);
        __pyx_v_site = __pyx_8;
        __pyx_8 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":94 */
        __pyx_17 = PyInt_AsSsize_t(__pyx_v_siteIndex); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
        __pyx_1 = PyInt_FromLong((((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->vector[__pyx_17])); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
        Py_DECREF(__pyx_v_instanceIndex);
        __pyx_v_instanceIndex = __pyx_1;
        __pyx_1 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":95 */
        __pyx_9 = PyObject_GetAttr(__pyx_v_site, __pyx_n_instances); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
        __pyx_10 = PyObject_GetItem(__pyx_9, __pyx_v_instanceIndex); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        Py_DECREF(__pyx_v_instance);
        __pyx_v_instance = __pyx_10;
        __pyx_10 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":97 */
        __pyx_11 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
        __pyx_2 = PyObject_GetAttr(__pyx_v_site, __pyx_n_segName); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
        __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_7, 0, __pyx_2);
        __pyx_2 = 0;
        __pyx_3 = PyObject_CallObject(__pyx_11, __pyx_7); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
        Py_DECREF(__pyx_11); __pyx_11 = 0;
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":98 */
        __pyx_5 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
        __pyx_6 = PyObject_GetAttr(__pyx_v_site, __pyx_n_resName); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
        __pyx_8 = PyTuple_New(1); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_8, 0, __pyx_6);
        __pyx_6 = 0;
        __pyx_1 = PyObject_CallObject(__pyx_5, __pyx_8); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":99 */
        __pyx_9 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
        __pyx_10 = PyObject_GetAttr(__pyx_v_site, __pyx_n_resSerial); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
        __pyx_2 = PyNumber_Remainder(__pyx_k22p, __pyx_10); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
        Py_DECREF(__pyx_10); __pyx_10 = 0;
        __pyx_11 = PyTuple_New(1); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_11, 0, __pyx_2);
        __pyx_2 = 0;
        __pyx_7 = PyObject_CallObject(__pyx_9, __pyx_11); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        Py_DECREF(__pyx_11); __pyx_11 = 0;
        Py_DECREF(__pyx_7); __pyx_7 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":100 */
        __pyx_3 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
        __pyx_6 = PyObject_GetAttr(__pyx_v_instance, __pyx_n_label); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
        __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_6);
        __pyx_6 = 0;
        __pyx_8 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_8); __pyx_8 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":101 */
        __pyx_1 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
        __pyx_10 = PyNumber_Remainder(__pyx_k22p, __pyx_v_instanceIndex); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
        __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_2, 0, __pyx_10);
        __pyx_10 = 0;
        __pyx_9 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_9); __pyx_9 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":102 */
        __pyx_11 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
        __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
        Py_INCREF(__pyx_v_substate);
        PyTuple_SET_ITEM(__pyx_7, 0, __pyx_v_substate);
        __pyx_6 = PyObject_CallObject(__pyx_11, __pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
        Py_DECREF(__pyx_11); __pyx_11 = 0;
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
      }

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":103 */
      __pyx_3 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Stop); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      __pyx_5 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      goto __pyx_L3;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  Py_XDECREF(__pyx_11);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.Print");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_table);
  Py_DECREF(__pyx_v_siteIndex);
  Py_DECREF(__pyx_v_substate);
  Py_DECREF(__pyx_v_j);
  Py_DECREF(__pyx_v_selectedSiteIndex);
  Py_DECREF(__pyx_v_site);
  Py_DECREF(__pyx_v_instanceIndex);
  Py_DECREF(__pyx_v_instance);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_meadModel);
  Py_DECREF(__pyx_v_title);
  Py_DECREF(__pyx_v_log);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_DefineSubstate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_DefineSubstate[] = "Define a substate.\n\n    |selectedSites| is a sequence of two-element sequences (segmentName, residueSerial)";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_DefineSubstate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_meadModel = 0;
  PyObject *__pyx_v_selectedSites = 0;
  PyObject *__pyx_v_ok;
  PyObject *__pyx_v_substateSiteIndex;
  PyObject *__pyx_v_selectedSegment;
  PyObject *__pyx_v_selectedSerial;
  PyObject *__pyx_v_foundSite;
  PyObject *__pyx_v_siteIndex;
  PyObject *__pyx_v_site;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  Integer __pyx_8;
  Integer __pyx_9;
  static char *__pyx_argnames[] = {"meadModel","selectedSites",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_meadModel, &__pyx_v_selectedSites)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_meadModel);
  Py_INCREF(__pyx_v_selectedSites);
  __pyx_v_ok = Py_None; Py_INCREF(Py_None);
  __pyx_v_substateSiteIndex = Py_None; Py_INCREF(Py_None);
  __pyx_v_selectedSegment = Py_None; Py_INCREF(Py_None);
  __pyx_v_selectedSerial = Py_None; Py_INCREF(Py_None);
  __pyx_v_foundSite = Py_None; Py_INCREF(Py_None);
  __pyx_v_siteIndex = Py_None; Py_INCREF(Py_None);
  __pyx_v_site = Py_None; Py_INCREF(Py_None);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":110 */
  __pyx_1 = PyObject_Length(__pyx_v_selectedSites); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(StateVector_AllocateSubstate(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_v_ok);
  __pyx_v_ok = __pyx_2;
  __pyx_2 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":111 */
  __pyx_3 = PyObject_IsTrue(__pyx_v_ok); if (__pyx_3 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_4 = (!__pyx_3);
  if (__pyx_4) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CLibraryError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_INCREF(__pyx_k5p);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k5p);
    __pyx_6 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_6, 0, 0);
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":114 */
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_INCREF(__pyx_v_selectedSites);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_selectedSites);
  __pyx_5 = PyObject_CallObject(((PyObject *)(&PyEnum_Type)), __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_6 = PyObject_GetIter(__pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  for (;;) {
    __pyx_2 = PyIter_Next(__pyx_6);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      break;
    }
    __pyx_5 = PyObject_GetIter(__pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = __Pyx_UnpackItem(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_v_substateSiteIndex);
    __pyx_v_substateSiteIndex = __pyx_2;
    __pyx_2 = 0;
    __pyx_2 = __Pyx_UnpackItem(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    __pyx_7 = PyObject_GetIter(__pyx_2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_v_selectedSegment);
    __pyx_v_selectedSegment = __pyx_2;
    __pyx_2 = 0;
    __pyx_2 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_v_selectedSerial);
    __pyx_v_selectedSerial = __pyx_2;
    __pyx_2 = 0;
    if (__Pyx_EndUnpack(__pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    if (__Pyx_EndUnpack(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":115 */
    Py_INCREF(Py_False);
    Py_DECREF(__pyx_v_foundSite);
    __pyx_v_foundSite = Py_False;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":117 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_meadModel, __pyx_n_meadSites); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_5 = PyObject_CallObject(((PyObject *)(&PyEnum_Type)), __pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    for (;;) {
      __pyx_7 = PyIter_Next(__pyx_2);
      if (!__pyx_7) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
        break;
      }
      __pyx_5 = PyObject_GetIter(__pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      __pyx_7 = __Pyx_UnpackItem(__pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
      Py_DECREF(__pyx_v_siteIndex);
      __pyx_v_siteIndex = __pyx_7;
      __pyx_7 = 0;
      __pyx_7 = __Pyx_UnpackItem(__pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
      Py_DECREF(__pyx_v_site);
      __pyx_v_site = __pyx_7;
      __pyx_7 = 0;
      if (__Pyx_EndUnpack(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_7 = PyObject_GetAttr(__pyx_v_site, __pyx_n_segName); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_7, __pyx_v_selectedSegment, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      __pyx_3 = __pyx_3 == 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__pyx_3) {
        __pyx_5 = PyObject_GetAttr(__pyx_v_site, __pyx_n_resSerial); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
        if (PyObject_Cmp(__pyx_5, __pyx_v_selectedSerial, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
        __pyx_3 = __pyx_3 == 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;
      }
      if (__pyx_3) {

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":119 */
        __pyx_8 = PyInt_AsLong(__pyx_v_siteIndex); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        __pyx_9 = PyInt_AsLong(__pyx_v_substateSiteIndex); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        StateVector_SetSubstateItem(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_8,__pyx_9);

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":120 */
        Py_INCREF(Py_True);
        Py_DECREF(__pyx_v_foundSite);
        __pyx_v_foundSite = Py_True;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":121 */
        goto __pyx_L6;
        goto __pyx_L7;
      }
      __pyx_L7:;
    }
    __pyx_L6:;
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":123 */
    __pyx_4 = PyObject_IsTrue(__pyx_v_foundSite); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    __pyx_3 = (!__pyx_4);
    if (__pyx_3) {
      __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_CLibraryError); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
      Py_INCREF(__pyx_v_selectedSegment);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_selectedSegment);
      Py_INCREF(__pyx_v_selectedSerial);
      PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_selectedSerial);
      __pyx_2 = PyNumber_Remainder(__pyx_k26p, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
      __pyx_2 = 0;
      __pyx_2 = PyObject_CallObject(__pyx_7, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __Pyx_Raise(__pyx_2, 0, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
      goto __pyx_L8;
    }
    __pyx_L8:;
  }
  Py_DECREF(__pyx_6); __pyx_6 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.DefineSubstate");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ok);
  Py_DECREF(__pyx_v_substateSiteIndex);
  Py_DECREF(__pyx_v_selectedSegment);
  Py_DECREF(__pyx_v_selectedSerial);
  Py_DECREF(__pyx_v_foundSite);
  Py_DECREF(__pyx_v_siteIndex);
  Py_DECREF(__pyx_v_site);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_meadModel);
  Py_DECREF(__pyx_v_selectedSites);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_IncrementSubstate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_IncrementSubstate[] = "Generate a new substate. \n\n    Return False after the incrementation has finished.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_IncrementSubstate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(StateVector_IncrementSubstate(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.IncrementSubstate");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetSubstate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_ResetSubstate[] = "Set all components of the substate to zero.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetSubstate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  StateVector_ResetSubstate(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_23ContinuumElectrostatics_11StateVector_StateVector(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_23ContinuumElectrostatics_11StateVector_StateVector(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}
static PyObject *__pyx_sq_item_23ContinuumElectrostatics_11StateVector_StateVector(PyObject *o, Py_ssize_t i) {
  PyObject *r;
  PyObject *x = PyInt_FromSsize_t(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static int __pyx_mp_ass_subscript_23ContinuumElectrostatics_11StateVector_StateVector(PyObject *o, PyObject *i, PyObject *v) {
  if (v) {
    return __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___setitem__(o, i, v);
  }
  else {
    PyErr_Format(PyExc_NotImplementedError,
      "Subscript deletion not supported by %s", o->ob_type->tp_name);
    return -1;
  }
}

static struct PyMethodDef __pyx_methods_23ContinuumElectrostatics_11StateVector_StateVector[] = {
  {"Increment", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Increment, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Increment},
  {"Reset", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Reset, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Reset},
  {"ResetToMaximum", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum},
  {"Print", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Print, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Print},
  {"DefineSubstate", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_DefineSubstate, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_DefineSubstate},
  {"IncrementSubstate", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_IncrementSubstate, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_IncrementSubstate},
  {"ResetSubstate", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetSubstate, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_ResetSubstate},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_StateVector = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_StateVector = {
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_23ContinuumElectrostatics_11StateVector_StateVector, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_StateVector = {
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__, /*mp_length*/
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___getitem__, /*mp_subscript*/
  __pyx_mp_ass_subscript_23ContinuumElectrostatics_11StateVector_StateVector, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_StateVector = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_23ContinuumElectrostatics_11StateVector_StateVector = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ContinuumElectrostatics.StateVector.StateVector", /*tp_name*/
  sizeof(struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_23ContinuumElectrostatics_11StateVector_StateVector, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_StateVector, /*tp_as_number*/
  &__pyx_tp_as_sequence_StateVector, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_StateVector, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_StateVector, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  "A class defining the state vector.", /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_23ContinuumElectrostatics_11StateVector_StateVector, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_23ContinuumElectrostatics_11StateVector_StateVector, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initStateVector(void); /*proto*/
PyMODINIT_FUNC initStateVector(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("StateVector", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_23ContinuumElectrostatics_11StateVector_StateVector) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "StateVector", (PyObject *)&__pyx_type_23ContinuumElectrostatics_11StateVector_StateVector) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_ptype_23ContinuumElectrostatics_11StateVector_StateVector = &__pyx_type_23ContinuumElectrostatics_11StateVector_StateVector;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":8 */
  __pyx_1 = PyList_New(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_INCREF(__pyx_n_logFile);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_logFile);
  Py_INCREF(__pyx_n_LogFileActive);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_LogFileActive);
  Py_INCREF(__pyx_n_CLibraryError);
  PyList_SET_ITEM(__pyx_1, 2, __pyx_n_CLibraryError);
  __pyx_2 = __Pyx_Import(__pyx_n_pCore, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_logFile); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_logFile, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_LogFileActive); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_LogFileActive, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_CLibraryError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_CLibraryError, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":10 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___lastchanged__, __pyx_k29p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":70 */
  Py_INCREF(Py_None);
  __pyx_d1 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d2 = Py_None;
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_logFile); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_d3 = __pyx_2;
  __pyx_2 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":134 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector");
}

static char *__pyx_filenames[] = {
  "ContinuumElectrostatics.StateVector.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
