#!/usr/bin/python
# 
# Usage: python make-sites.py monomer.pqr > monomer.sites
# 
# CRH, CRT = IrisFP chromophore, histidine and tyrosine part, respectively
# 
# CRB, CRC = IFP chromophore,  carboxylic groups of ring B and C, respectively
# 
from sys import argv

titrate = ("ARG", "ASP", "GLU", "HIS", "LYS", "LYR", "TYR", "CYS", "CRH", "CRT", "CRB", "CRC")
pqr     = open (argv[1]).readlines ()
res     = []

for f in pqr:
  if f[:4] == "ATOM":
    rname = f[17:20]
    rnumb = f[20:26]

    if rname in titrate:
      rec   = "%6s%6s" % (rnumb, rname)  
      if not rec in res:
        res.append (rec)

for r in res:
  print r
