#!/usr/bin/python
#--------------------------------------------------
#  Recount residues in a PDB file
# 
#  Usage: pdb_recount START_NUMBER file.pdb
#         cat file.pdb | pdb_recount START_NUMBER
#--------------------------------------------------
from sys import argv, stdin

snum = int (argv[1])
F    = stdin.readlines () if len (argv) < 3 else open (argv[2]).readlines ()

an = 1
pn = 0
rn = snum - 1

for f in F:
  if f[:6] in ("ATOM  ", "HETATM"):
    anum, rnum = map (int, (f[7:12], f[22:26]))

    if rnum != pn:
      pn  = rnum
      rn += 1
    print ("%s%5d %s%4d%s" % (f[:6], an, f[12:22], rn, f[26:-1]))

    an += 1
  else:
    print f[:-1]
