/* Generated by Pyrex 0.9.8.5 on Tue May 13 20:29:28 2014 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "StateVector.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from ContinuumElectrostatics.StateVector */

struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector {
  PyObject_HEAD
  StateVector *cObject;
};


static PyTypeObject *__pyx_ptype_23ContinuumElectrostatics_11StateVector_StateVector = 0;

/* Declarations from implementation of ContinuumElectrostatics.StateVector */


static char __pyx_k1[] = "meadSites";
static char __pyx_k2[] = "instances";
static char __pyx_k3[] = "LogFileActive";
static char __pyx_k4[] = "GetTable";
static char __pyx_k5[] = "columns";
static char __pyx_k6[] = "Start";
static char __pyx_k7[] = "Title";
static char __pyx_k8[] = "State vector";
static char __pyx_k9[] = "Heading";
static char __pyx_k10[] = "Site";
static char __pyx_k11[] = "columnSpan";
static char __pyx_k12[] = "Instance";
static char __pyx_k13[] = "range";
static char __pyx_k14[] = "Entry";
static char __pyx_k15[] = "segName";
static char __pyx_k16[] = "resName";
static char __pyx_k17[] = "resNum";
static char __pyx_k18[] = "%s";
static char __pyx_k19[] = "label";
static char __pyx_k20[] = "%d";
static char __pyx_k21[] = "Stop";
static char __pyx_k22[] = "$Revision: 14 $";
static char __pyx_k23[] = "__revision__";
static char __pyx_k24[] = "pCore";
static char __pyx_k25[] = "logFile";

static PyObject *__pyx_n_Entry;
static PyObject *__pyx_n_GetTable;
static PyObject *__pyx_n_Heading;
static PyObject *__pyx_n_Instance;
static PyObject *__pyx_n_LogFileActive;
static PyObject *__pyx_n_Site;
static PyObject *__pyx_n_Start;
static PyObject *__pyx_n_Stop;
static PyObject *__pyx_n_Title;
static PyObject *__pyx_n___revision__;
static PyObject *__pyx_n_columnSpan;
static PyObject *__pyx_n_columns;
static PyObject *__pyx_n_instances;
static PyObject *__pyx_n_label;
static PyObject *__pyx_n_logFile;
static PyObject *__pyx_n_meadSites;
static PyObject *__pyx_n_pCore;
static PyObject *__pyx_n_range;
static PyObject *__pyx_n_resName;
static PyObject *__pyx_n_resNum;
static PyObject *__pyx_n_segName;

static PyObject *__pyx_k8p;
static PyObject *__pyx_k18p;
static PyObject *__pyx_k20p;
static PyObject *__pyx_k22p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_Entry, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_GetTable, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_Heading, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_Instance, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_LogFileActive, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_Site, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_Start, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_Stop, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_Title, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n___revision__, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_columnSpan, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_columns, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_instances, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_label, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_logFile, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_meadSites, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_pCore, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_range, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_resName, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_resNum, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_segName, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k18p, 0, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k20p, 0, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k22p, 0, __pyx_k22, sizeof(__pyx_k22)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;
static PyObject *__pyx_d2;
static PyObject *__pyx_d3;


/* Implementation of ContinuumElectrostatics.StateVector */

static Py_ssize_t __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__(PyObject *__pyx_v_self); /*proto*/
static Py_ssize_t __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__(PyObject *__pyx_v_self) {
  Py_ssize_t __pyx_r;
  Py_INCREF(__pyx_v_self);
  __pyx_r = ((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->length;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index); /*proto*/
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(StateVector_GetItem(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  return __pyx_r;
}

static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value); /*proto*/
static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value) {
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);
  Py_INCREF(__pyx_v_value);
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_value); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  StateVector_SetItem(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject,__pyx_1,__pyx_2);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.__setitem__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  Py_DECREF(__pyx_v_value);
  return __pyx_r;
}

static void __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);
  StateVector_Deallocate(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Increment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Increment[] = "Generate a new state incrementing the state vector.\n\n    Return False after the incrementation has finished.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Increment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(StateVector_Increment(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.Increment");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Reset(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Reset[] = "Set all components of the vector to zero.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Reset(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  StateVector_Reset(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum[] = "Set all components of the vector to their maximum values.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  StateVector_ResetToMaximum(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_continuumElectrostaticModel = 0;
  PyObject *__pyx_v_nsites;
  PyObject *__pyx_v_isite;
  PyObject *__pyx_v_site;
  PyObject *__pyx_v_ninstances;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"continuumElectrostaticModel",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_continuumElectrostaticModel)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_continuumElectrostaticModel);
  __pyx_v_nsites = Py_None; Py_INCREF(Py_None);
  __pyx_v_isite = Py_None; Py_INCREF(Py_None);
  __pyx_v_site = Py_None; Py_INCREF(Py_None);
  __pyx_v_ninstances = Py_None; Py_INCREF(Py_None);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":57 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_continuumElectrostaticModel, __pyx_n_meadSites); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  __pyx_2 = PyObject_Length(__pyx_1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromSsize_t(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(__pyx_v_nsites);
  __pyx_v_nsites = __pyx_1;
  __pyx_1 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":58 */
  __pyx_3 = PyInt_AsLong(__pyx_v_nsites); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  ((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject = StateVector_Allocate(__pyx_3);

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":62 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_continuumElectrostaticModel, __pyx_n_meadSites); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject *)(&PyEnum_Type)), __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyObject_GetIter(__pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_4);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
      break;
    }
    __pyx_5 = PyObject_GetIter(__pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_v_isite);
    __pyx_v_isite = __pyx_1;
    __pyx_1 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_v_site);
    __pyx_v_site = __pyx_1;
    __pyx_1 = 0;
    if (__Pyx_EndUnpack(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":63 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_site, __pyx_n_instances); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_2 = PyObject_Length(__pyx_1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_5 = PyInt_FromSsize_t(__pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ninstances);
    __pyx_v_ninstances = __pyx_5;
    __pyx_5 = 0;

    /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":64 */
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_5 = PyNumber_Subtract(__pyx_v_ninstances, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_2 = PyInt_AsSsize_t(__pyx_v_isite); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    (((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->maxvector[__pyx_2]) = __pyx_3;
  }
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_nsites);
  Py_DECREF(__pyx_v_isite);
  Py_DECREF(__pyx_v_site);
  Py_DECREF(__pyx_v_ninstances);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_continuumElectrostaticModel);
  return __pyx_r;
}

static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Print(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Print[] = "Print the state vector.";
static PyObject *__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Print(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_continuumElectrostaticModel = 0;
  PyObject *__pyx_v_title = 0;
  PyObject *__pyx_v_log = 0;
  PyObject *__pyx_v_table;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_site;
  PyObject *__pyx_v_protonation;
  PyObject *__pyx_v_instance;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  Py_ssize_t __pyx_11;
  static char *__pyx_argnames[] = {"continuumElectrostaticModel","title","log",0};
  __pyx_v_continuumElectrostaticModel = __pyx_d1;
  __pyx_v_title = __pyx_d2;
  __pyx_v_log = __pyx_d3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_continuumElectrostaticModel, &__pyx_v_title, &__pyx_v_log)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_continuumElectrostaticModel);
  Py_INCREF(__pyx_v_title);
  Py_INCREF(__pyx_v_log);
  __pyx_v_table = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_site = Py_None; Py_INCREF(Py_None);
  __pyx_v_protonation = Py_None; Py_INCREF(Py_None);
  __pyx_v_instance = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_LogFileActive); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_INCREF(__pyx_v_log);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_log);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    __pyx_4 = PyObject_IsTrue(__pyx_v_continuumElectrostaticModel); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    if (__pyx_4) {

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":71 */
      __pyx_1 = PyObject_GetAttr(__pyx_v_log, __pyx_n_GetTable); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_6 = PyInt_FromLong(7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_7 = PyInt_FromLong(7); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_8 = PyInt_FromLong(8); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_9 = PyInt_FromLong(8); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      __pyx_10 = PyList_New(5); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      PyList_SET_ITEM(__pyx_10, 0, __pyx_5);
      PyList_SET_ITEM(__pyx_10, 1, __pyx_6);
      PyList_SET_ITEM(__pyx_10, 2, __pyx_7);
      PyList_SET_ITEM(__pyx_10, 3, __pyx_8);
      PyList_SET_ITEM(__pyx_10, 4, __pyx_9);
      __pyx_5 = 0;
      __pyx_6 = 0;
      __pyx_7 = 0;
      __pyx_8 = 0;
      __pyx_9 = 0;
      if (PyDict_SetItem(__pyx_3, __pyx_n_columns, __pyx_10) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_5 = PyEval_CallObjectWithKeywords(__pyx_1, __pyx_2, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_v_table);
      __pyx_v_table = __pyx_5;
      __pyx_5 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":72 */
      __pyx_6 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Start); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
      __pyx_7 = PyObject_CallObject(__pyx_6, 0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":73 */
      __pyx_4 = __pyx_v_title == Py_None;
      if (__pyx_4) {
        __pyx_8 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Title); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
        __pyx_9 = PyTuple_New(1); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
        Py_INCREF(__pyx_k8p);
        PyTuple_SET_ITEM(__pyx_9, 0, __pyx_k8p);
        __pyx_10 = PyObject_CallObject(__pyx_8, __pyx_9); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        Py_DECREF(__pyx_10); __pyx_10 = 0;
        goto __pyx_L4;
      }
      /*else*/ {
        __pyx_1 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Title); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
        __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
        Py_INCREF(__pyx_v_title);
        PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_title);
        __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
      }
      __pyx_L4:;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":78 */
      __pyx_5 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Heading); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      Py_INCREF(__pyx_n_Site);
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_n_Site);
      __pyx_7 = PyDict_New(); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      __pyx_8 = PyInt_FromLong(3); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      if (PyDict_SetItem(__pyx_7, __pyx_n_columnSpan, __pyx_8) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      Py_DECREF(__pyx_8); __pyx_8 = 0;
      __pyx_9 = PyEval_CallObjectWithKeywords(__pyx_5, __pyx_6, __pyx_7); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      Py_DECREF(__pyx_9); __pyx_9 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":79 */
      __pyx_10 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Heading); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
      __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
      Py_INCREF(__pyx_n_Instance);
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_n_Instance);
      __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
      if (PyDict_SetItem(__pyx_2, __pyx_n_columnSpan, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_8 = PyEval_CallObjectWithKeywords(__pyx_10, __pyx_1, __pyx_2); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_8); __pyx_8 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":81 */
      __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      __pyx_6 = PyInt_FromLong(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      __pyx_7 = PyInt_FromLong(((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->length); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      __pyx_9 = PyTuple_New(2); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_9, 0, __pyx_6);
      PyTuple_SET_ITEM(__pyx_9, 1, __pyx_7);
      __pyx_6 = 0;
      __pyx_7 = 0;
      __pyx_3 = PyObject_CallObject(__pyx_5, __pyx_9); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_10 = PyObject_GetIter(__pyx_3); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      for (;;) {
        __pyx_1 = PyIter_Next(__pyx_10);
        if (!__pyx_1) {
          if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
          break;
        }
        Py_DECREF(__pyx_v_i);
        __pyx_v_i = __pyx_1;
        __pyx_1 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":82 */
        __pyx_2 = PyObject_GetAttr(__pyx_v_continuumElectrostaticModel, __pyx_n_meadSites); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
        __pyx_8 = PyObject_GetItem(__pyx_2, __pyx_v_i); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_v_site);
        __pyx_v_site = __pyx_8;
        __pyx_8 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":83 */
        __pyx_11 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
        __pyx_6 = PyInt_FromLong((((struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector *)__pyx_v_self)->cObject->vector[__pyx_11])); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
        Py_DECREF(__pyx_v_protonation);
        __pyx_v_protonation = __pyx_6;
        __pyx_6 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":85 */
        __pyx_7 = PyObject_GetAttr(__pyx_v_site, __pyx_n_instances); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
        __pyx_5 = PyObject_GetItem(__pyx_7, __pyx_v_protonation); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(__pyx_v_instance);
        __pyx_v_instance = __pyx_5;
        __pyx_5 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":86 */
        __pyx_9 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
        __pyx_3 = PyObject_GetAttr(__pyx_v_site, __pyx_n_segName); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
        __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
        __pyx_3 = 0;
        __pyx_2 = PyObject_CallObject(__pyx_9, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":87 */
        __pyx_8 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
        __pyx_6 = PyObject_GetAttr(__pyx_v_site, __pyx_n_resName); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
        __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
        __pyx_6 = 0;
        __pyx_5 = PyObject_CallObject(__pyx_8, __pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":88 */
        __pyx_3 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        __pyx_9 = PyObject_GetAttr(__pyx_v_site, __pyx_n_resNum); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_1, 0, __pyx_9);
        __pyx_9 = 0;
        __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":89 */
        __pyx_6 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
        __pyx_8 = PyObject_GetAttr(__pyx_v_instance, __pyx_n_label); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
        __pyx_7 = PyNumber_Remainder(__pyx_k18p, __pyx_8); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_7);
        __pyx_7 = 0;
        __pyx_9 = PyObject_CallObject(__pyx_6, __pyx_5); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_9); __pyx_9 = 0;

        /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":90 */
        __pyx_3 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Entry); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
        __pyx_1 = PyNumber_Remainder(__pyx_k20p, __pyx_v_protonation); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
        __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
        __pyx_1 = 0;
        __pyx_8 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_8); __pyx_8 = 0;
      }
      Py_DECREF(__pyx_10); __pyx_10 = 0;

      /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":91 */
      __pyx_7 = PyObject_GetAttr(__pyx_v_table, __pyx_n_Stop); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
      __pyx_6 = PyObject_CallObject(__pyx_7, 0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      goto __pyx_L3;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector.StateVector.Print");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_table);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_site);
  Py_DECREF(__pyx_v_protonation);
  Py_DECREF(__pyx_v_instance);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_continuumElectrostaticModel);
  Py_DECREF(__pyx_v_title);
  Py_DECREF(__pyx_v_log);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_23ContinuumElectrostatics_11StateVector_StateVector(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_23ContinuumElectrostatics_11StateVector_StateVector(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}
static PyObject *__pyx_sq_item_23ContinuumElectrostatics_11StateVector_StateVector(PyObject *o, Py_ssize_t i) {
  PyObject *r;
  PyObject *x = PyInt_FromSsize_t(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static int __pyx_mp_ass_subscript_23ContinuumElectrostatics_11StateVector_StateVector(PyObject *o, PyObject *i, PyObject *v) {
  if (v) {
    return __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___setitem__(o, i, v);
  }
  else {
    PyErr_Format(PyExc_NotImplementedError,
      "Subscript deletion not supported by %s", o->ob_type->tp_name);
    return -1;
  }
}

static struct PyMethodDef __pyx_methods_23ContinuumElectrostatics_11StateVector_StateVector[] = {
  {"Increment", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Increment, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Increment},
  {"Reset", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Reset, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Reset},
  {"ResetToMaximum", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_ResetToMaximum},
  {"Print", (PyCFunction)__pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector_Print, METH_VARARGS|METH_KEYWORDS, __pyx_doc_23ContinuumElectrostatics_11StateVector_11StateVector_Print},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_StateVector = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_StateVector = {
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_23ContinuumElectrostatics_11StateVector_StateVector, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_StateVector = {
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___len__, /*mp_length*/
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___getitem__, /*mp_subscript*/
  __pyx_mp_ass_subscript_23ContinuumElectrostatics_11StateVector_StateVector, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_StateVector = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_23ContinuumElectrostatics_11StateVector_StateVector = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ContinuumElectrostatics.StateVector.StateVector", /*tp_name*/
  sizeof(struct __pyx_obj_23ContinuumElectrostatics_11StateVector_StateVector), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_23ContinuumElectrostatics_11StateVector_StateVector, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_StateVector, /*tp_as_number*/
  &__pyx_tp_as_sequence_StateVector, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_StateVector, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_StateVector, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  "A class defining the state vector.", /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_23ContinuumElectrostatics_11StateVector_StateVector, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_23ContinuumElectrostatics_11StateVector_11StateVector___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_23ContinuumElectrostatics_11StateVector_StateVector, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initStateVector(void); /*proto*/
PyMODINIT_FUNC initStateVector(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("StateVector", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_23ContinuumElectrostatics_11StateVector_StateVector) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "StateVector", (PyObject *)&__pyx_type_23ContinuumElectrostatics_11StateVector_StateVector) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_ptype_23ContinuumElectrostatics_11StateVector_StateVector = &__pyx_type_23ContinuumElectrostatics_11StateVector_StateVector;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":9 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___revision__, __pyx_k22p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":12 */
  __pyx_1 = PyList_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_INCREF(__pyx_n_logFile);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_logFile);
  Py_INCREF(__pyx_n_LogFileActive);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_LogFileActive);
  __pyx_2 = __Pyx_Import(__pyx_n_pCore, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_logFile); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_logFile, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_LogFileActive); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_LogFileActive, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/mikolaj/devel/ContinuumElectrostatics/extensions/pyrex/ContinuumElectrostatics.StateVector.pyx":67 */
  Py_INCREF(Py_None);
  __pyx_d1 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d2 = Py_None;
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_logFile); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_d3 = __pyx_2;
  __pyx_2 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ContinuumElectrostatics.StateVector");
}

static char *__pyx_filenames[] = {
  "ContinuumElectrostatics.StateVector.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
