#!/usr/bin/python
#================================================
#  Usage: segid SGID file.pdb [file2.pdb [...]]
#   or
#  cat file.pdb [file2.pdb [...]] | segid SGID
#================================================
from sys import argv, stdin

segid = argv[1]
if len (argv) > 2:
  F = open (argv[2]).readlines ()
else:
  F = stdin.readlines ()

for f in F:
  if f[:6] in ("ATOM  ", "HETATM"):
    print ("%s%22s" % (f[:54], segid))

print ("END")
