#!/usr/bin/python

# Recount residues in a PDB file
#
# Usage: pdb-recount START_NUMBER file.pdb
#           or
#        cat file.pdb | pdb-recount START_NUMBER

# from sys import argv, stdin
# 
# start_num = int(argv[1])
# F         = stdin.readlines() if len(argv) < 3 else open(argv[2]).readlines()
# 
# #---------------------
# pn = 0
# rn = start_num - 1
# 
# for f in F:
#   if f[:4] == "ATOM" or f[:6] == "HETATM":
#     res_num = f[22:26]
# 
#     if res_num != pn:
#       pn  = res_num
#       rn += 1
#     print("%s%4d%s" % (f[:22], rn, f[26:-1]))
#   else:
#     print f[:-1]


from sys import argv, stdin

F  = stdin.readlines() if len(argv) < 2 else open(argv[1]).readlines()

pn, rn, an = 0, 0, 1

for f in F:
  if f[:4] == "ATOM" or f[:6] == "HETATM":
    at_num  = f[6:11]
    res_num = f[22:26]

    if res_num != pn:
      pn = res_num
      rn += 1

    print("%s%5s%s%4d%s" % (f[:6], at_num, f[11:22], rn, f[26:-1]))
    an += 1    

  else:
    print f[:-1]
